import { Sparkles, Check } from "lucide-react";
import { TypeLine } from "./TypeLine";

const SECTIONS = [
  {
    emoji: "💵",
    label: "Income",
    text: "Dues are landing on time — $61,940 collected this quarter, a 98% on-time rate.",
  },
  {
    emoji: "📊",
    label: "Expenses",
    text: "Spending is $6,905 under budget, mostly deferred landscaping. Insurance renews in March (+12%).",
  },
  {
    emoji: "🏦",
    label: "Reserves",
    text: "Reserves sit at 28% funded against a $1.6M target — below the 70% comfort line. A $480/mo bump closes the gap over ten years.",
  },
  {
    emoji: "📥",
    label: "Collections",
    text: "36 units are past due ($32,303). Three accounts crossed 90 days and may need the attorney.",
  },
] as const;

/**
 * The AI "Treasurer Brief" card — gold left border, sparkle header,
 * emoji-labeled themed sections, an approved footer. Matches the app's
 * AISummaryCard. Pass `typing` to type the first section in (hero only).
 */
export function TreasurerBriefMock({ typing = false }: { typing?: boolean }) {
  return (
    <div
      className="card-shadow rounded-[20px] border border-line bg-white p-5"
      style={{ borderLeft: "3px solid #D4AF37" }}
    >
      <div className="mb-4 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <Sparkles size={16} className="text-gold" aria-hidden />
          <h3 className="text-sm font-semibold text-navy">Treasurer Brief</h3>
        </div>
        <span className="font-data text-[10px] uppercase tracking-[0.1em] text-mute">
          Q2 · FY2026
        </span>
      </div>

      <div className="grid grid-cols-1 gap-x-6 gap-y-3.5 sm:grid-cols-2">
        {SECTIONS.map((s, i) => (
          <div key={s.label} className="flex gap-2.5">
            <span className="text-[15px] leading-snug" aria-hidden>
              {s.emoji}
            </span>
            <div>
              <p className="text-[11px] font-bold uppercase tracking-[0.03em] text-navy">
                {s.label}
              </p>
              <p className="mt-0.5 text-[13px] leading-relaxed text-slate">
                {typing && i === 0 ? <TypeLine text={s.text} /> : s.text}
              </p>
            </div>
          </div>
        ))}
      </div>

      <div className="mt-5 flex items-center gap-1.5 border-t border-line pt-3.5">
        <Check size={13} className="text-healthy" strokeWidth={2.5} aria-hidden />
        <p className="text-xs text-mute">
          Generated by AI · Approved by the board · Jun 1, 2026
        </p>
      </div>
    </div>
  );
}
